name: Validate JSON
on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Validate JSON
      uses: docker://orrosenblatt/validate-json-action:latest
      env:
          INPUT_SCHEMA: /json-schema/library.json
          INPUT_JSONS: Library.json
